name: Test AAPL SEC Data

on:
  workflow_dispatch:

jobs:
  get-sec-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Run SEC script
        run: python scripts/get_aapl_10q.py
